config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :sessions, only: [:new, :create, :destroy]

  get "login" => 'sessions#new'
  delete "logout" => 'sessions#destroy'

  resources :users

  resources :profiles

  resources :locations

  resources :searchs, only: [:index, :new]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :profile
  has_many :locations, as: :locationable, class_name: "Location"

  validates :username, length: { :minimum => 1}, uniqueness: true
  validates :email, uniqueness: true
  validates_format_of :email, :with => /@.*[.]com\z/
  #validates :password, :allow_nil => false#, length: { in: (5..26) }

  before_create :generate_token

  def generate_token
    begin
      self[:auth_token] = SecureRandom.urlsafe_base64
    end while User.exists?(:auth_token => self[:auth_token])
  end

  def regenerate_auth_token
    self.auth_token = nil
    generate_token
    save!
  end

  # def has_profile?
  #   !!self.profile
  # end
  # helper_method :has_profile?
end

app/controllers/users_controller.rb
require 'factual'

class UsersController < ApplicationController
  include ApplicationHelper

  #skip_before_action :verify_authenticity_token

  def show
    @user = User.find(params[:id])
    if @user.profile
      address = @user.profile.address
      if @user.profile.location
        longitude = @user.profile.location.longitude
        latitude = @user.profile.location.latitude

        
        @loc = static_map_for(latitude, longitude, address)
        @loc = @loc + add_markers_map(@user) + add_key

      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(whitelisted_user_params)
    if @user.save
      sign_in(@user)
      #User.delay(queue: "email", priority: 28, run_at: 5.seconds.from_now).send_welcome_email(@user.id)
      flash[:success] = "User was created"
      redirect_to @user
    else
      flash[:error] = "User was NOT! created"
      render :new
    end
  end

  def edit
  end

  def delete
  end

  def update
  end

  private

    def add_markers_map(user)
      str = ""
      user.locations.each do |loc|
        str += "&markers=color:green\%7Clabel:O\%7C#{loc.latitude},#{loc.longitude}"
      end
      str
    end

    def whitelisted_user_params
      params.
        require(:user).
        permit( :username,
                :email,
                :password,
                :password_confirmation)
    end

    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<ul>

<%= form_for @user do |user_fields| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <%= user_fields.label :username %>
  <br>
  <%= user_fields.text_field :username %>
  <br>
  <%= user_fields.label :email %>
  <br>
  <%= user_fields.text_field :email %>
  <br>
  <%= user_fields.label :password %>
  <br>
  <%= user_fields.password_field :password %>
  <br>
  <%= user_fields.label :password_confirmation %>
  <br>
  <%= user_fields.password_field :password_confirmation %>
  <br>
  <br>

  <button type="submit" class="btn btn-default">
    <%= user_fields.submit "Sign Up" %>
  </button>
<% end %>

</ul>

app/views/users/show.html.erb
<div class="jumbotron" id="big-body">
  <div class="container">
    <div class="row" id="profile-row">



      <% if current_user.profile.nil? %>
      <ul>
        <h3>
          Step 1: Create Profile
          <br>
          Step 2: Create Location
          <br>
          Step 3: Profit..
        <h3>
      </h1>
        <ul>
          <button> <%= link_to "Create Profile", new_profile_path %> </button>
        </ul>

      <% else %>
        
        <code> Display Profile </code>

        <div class="row">
          <%= render partial: "shared/profile", locals: { profile: @user.profile} %>
        </div>
        
      <% end %>
    </div>

    <%if current_user.profile %>
      <div class="row" id="location-row">
        <button> <%= link_to "Find Your Location", new_location_path %> </button>
      </div>
    <% end %>

  </div>
</div>

<% if current_user.profile && current_user.profile.location %>
  <div id="image-holder"> 
    <img class="displayed" src=<%= @loc %> alt="gmap">
  </div>
<% end %>