config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :sessions, only: [:new, :create, :destroy]

  get "login" => 'sessions#new'
  delete "logout" => 'sessions#destroy'

  resources :users

  resources :profiles

  resources :locations

  resources :searchs, only: [:index, :new]
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="main-nav">
    <div class="col-xs-3">
      <div class="navbar-header">
         <a class="navbar-left brand-img">
          <h5><img src="https://cdn1.iconfinder.com/data/icons/virtual-keyboard/512/geo-poi-pointer-round-atm-function-512.png", style="width: 20px">
          My POI Finder Web App <small>by Adrianmonster
          </small> </a></h5>
         </a>
         
      </div>
    </div>
    <div class="col-xs-9">

      <ul class="nav nav-pills">
        <li>
          <span class="label label-info">
            NAV_BAR
          </span>
        </li>
        <% if signed_in_user? %>
          <li> 
            <%= link_to "User", current_user %> 
          </li>
          
            <% if current_user.profile %>
              <% if current_user.profile.location %>
              <li> 
                <%= link_to "Your Location", location_path(current_user.profile.location) %> 
              </li>
              <li> 
                <%= link_to "Stuff Near You", locations_path %>
              </li>
              <li> 
                <%= link_to "Search(BETA)", searchs_path %>  
              </li>
              <% end %>    
            <% end %>
          
        <% end %>
          <li>
        


          <span class="label label-success">
            User
          </span>
        </li>
    
         
          <% if signed_in_user? %>
            <li>
              <%= link_to "logout", session_path(current_user), method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "login", login_path %> 
            </li>
            <li>
              <%= link_to "Sign Up", new_user_path %>
           </li>
          <% end %>
        

        
      </ul>
    </div>
</nav>

app/views/shared/_profile.html.erb
<div>
  <ul>
  <h2>
    :: <kbd><%= profile.first_name %> <%= profile.last_name %>s</kbd> Kickass Profile ::
  </h2>

    <table class="table table-striped table-hover table-bordered">
      <tr>
        <th>
          address
        </th>
        <th>
          zip
        </th>
        <th>
          city
        </th>
        <th>
          state
        </th>
      </tr>

      <tr>

        <th>
          <%= profile.address %>
        </th>
        <th>
          <%= profile.zip %>
        </th>
        <th>
          <%= profile.city %>
        </th>
        <th>
          <%= profile.state %>
        </th>
      </tr>
    </table>
  </ul>
</div>