config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :sessions, only: [:new, :create, :destroy]

  get "login" => 'sessions#new'
  delete "logout" => 'sessions#destroy'

  resources :users

  resources :profiles

  resources :locations

  resources :searchs, only: [:index, :new]
end

app/controllers/searchs_controller.rb
require 'factual'

class SearchsController < ApplicationController
  def index
  end
  def new
    
    @factual = Factual.new(Rails.application.secrets.OAUTH_KEY, Rails.application.secrets.OAUTH_SECRET)
     
    @user = current_user
    if params[:query_dist].to_i
      dist = params[:query_dist].to_i > 0 ? params[:query_dist] : 1
      name = params[:query_name] if params[:query_name]
      if @user.profile
        address = @user.profile.address
        if @user.profile.location
          longitude = @user.profile.location.longitude
          latitude = @user.profile.location.latitude
          @places_near_me = @factual.table("places-us").search("#{name}").geo("$circle" => {"$center" => [latitude, longitude], "$meters" => dist }).rows
        
        end
      end
    end
  end


end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/index.html.erb
<br>



<ul>
  <ul class="nav">
    This is the SEARCH_FORM that works with the <kbd>Factual-API gem</kbd> to find your favorite places near you <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> 
  </ul>

  <br>

  <%= form_tag(new_search_path, :method => "get", id: "search-form") do %>
    <p>
      <%= text_field_tag :query_dist, nil, placeholder: "within distance? ie: 200" %>
      <br>
      <%= text_field_tag :query_name, nil, placeholder: "search for name? ie: burger" %>
      <%= submit_tag "search" %>
    </p>

  <% end %>
</ul>

  

app/views/searchs/new.html.erb
<br>
<ul>
<% if !@places_near_me.empty? %>
  
  <code> Search results... <%= @places_near_me.length %> POIs Near You </code>
  
  <br>

  
  <% @places_near_me.each do |places| %>
    <br>

    <div id="image-holder">
      <img src=<%= (static_map_for(places["latitude"], places["longitude"], places["address"]) + add_key) %> alt="gmap">
    </div>

    <br>

    <button type="button" class="btn btn-warning"> <%= link_to "Add To My Locations", locations_path(:user_id => current_user.id, :location => { :address => places["address"] } ), method: :create %> </button>

    </br>

    <table class="table table-striped table-hover">
      <tr>
        <th>
          name
        </th>
        <th>
          address
        </th>
        <th>
          neighborhood
        </th>
        <th>
          website
        </th>
        <th>
          <%= Date.today.strftime("%A") %>
        </th>
        <th>
          category labels
        </th>
        <th>
          latitude
        </th>
        <th>
          longitude
        </th>
      </tr>
      <tr>
        <td>
          <%= places["name"] %>
        </td>
        <td>
          <%= places["address"] %>
        </td>
        <td>
          <% if places["neighborhood"] %>
            <%= places["neighborhood"][0..1].join(", ") %>
          <% end %>
        </td>
        <td>
          <%= link_to places["website"], places["website"] %>
        </td>
        <td>
          <% if places["hours"] %>
            <ul>
              <% places["hours"]["#{Date.today.strftime("%A").downcase}"].each do |time| %>
                <li>
                  <%= time[0] %> to <%= time[1] %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </td>
        <td>
            <% if places["category_labels"] %>
            <li>
              <%= places["category_labels"][0].join(", ") %>
            </li>
          <% end %>
        </td>
        <td>
          <%= places["latitude"] %>
        </td>
        <td>
          <%= places["longitude"] %>
        </td>
      </tr>
    </table>
    


  <% end %>
  </tr>
<% else %>
  YOU LIVE IN A DESERT JUST ROT AND IED ALREADY <h1>-RESTINPEACEHARAMBE- </h1>
<% end %>

</ul>