config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :sessions, only: [:new, :create, :destroy]

  get "login" => 'sessions#new'
  delete "logout" => 'sessions#destroy'

  resources :users

  resources :profiles

  resources :locations

  resources :searchs, only: [:index, :new]
end

app/models/location.rb
class Location < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode

  belongs_to :locationable, :polymorphic => true
end

app/controllers/locations_controller.rb
require 'factual'

class LocationsController < ApplicationController


  def index
    @factual = Factual.new(Rails.application.secrets.OAUTH_KEY, Rails.application.secrets.OAUTH_SECRET)
    @user = current_user
    if @user.profile
      address = @user.profile.address
      if @user.profile.location
        longitude = @user.profile.location.longitude
        latitude = @user.profile.location.latitude
        @places_near_me = @factual.table("places-us").geo("$circle" => {"$center" => [latitude, longitude], "$meters" => 500}).rows
      end
    end
  end

  def new
    @location = Location.new
  end

  def create
    @locationable = get_locationable_resource
    

    if @locationable.nil?
      @location = current_user.profile.location = Location.new(
        whitelisted_location_params)
    elsif @locationable.class == User
      @location = @locationable.locations.build(whitelisted_location_params)
    else
      @location = current_user.profile.location
    end

    if @location.save
      flash[:success] = "Location has been generated"

      redirect_to current_user
    else
      flash[:success] = "Location has NOT! been generated"
      render :new
    end

  end

  def show
    @location = Location.find(params[:id])
  end

  

  private

  def get_locationable_resource
    resource = User.find(params[:user_id]) if params[:user_id]
    resource = Profile.find(params[:profile_id]) if params[:profile_id]
    resource
  end

  def whitelisted_location_params
      params.
        require(:location).
        permit( :address)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/index.html.erb
<br>
<ul>
<% if !@places_near_me.empty? %>
  
  <code> Search results... <%= @places_near_me.length %> POIs Near You </code>
  
  <br>

  
  <% @places_near_me[1..-1].each do |places| %>
    <br>

    <div id="image-holder">
      <img src=<%= (static_map_for(places["latitude"], places["longitude"], places["address"]) + add_key) %> alt="gmap">
    </div>

    <br>

    <button type="button" class="btn btn-warning"> <%= link_to "Add To My Locations", locations_path(:user_id => current_user.id, :location => { :address => places["address"] } ), method: :create %> </button>

    </br>

    <table class="table table-striped table-hover">
      <tr>
        <th>
          name
        </th>
        <th>
          address
        </th>
        <th>
          neighborhood
        </th>
        <th>
          website
        </th>
        <th>
          <%= Date.today.strftime("%A") %>
        </th>
        <th>
          category labels
        </th>
        <th>
          latitude
        </th>
        <th>
          longitude
        </th>
      </tr>
      <tr>
        <td>
          <%= places["name"] %>
        </td>
        <td>
          <%= places["address"] %>
        </td>
        <td>
          <% if places["neighborhood"] %>
            <%= places["neighborhood"][0..1].join(", ") %>
          <% end %>
        </td>
        <td>
          <%= link_to places["website"], places["website"] %>
        </td>
        <td>
          <% if places["hours"] %>
            <ul>
              <% places["hours"]["#{Date.today.strftime("%A").downcase}"].each do |time| %>
                <li>
                  <%= time[0] %> to <%= time[1] %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </td>
        <td>
            <% if places["category_labels"] %>
            <li>
              <%= places["category_labels"][0].join(", ") %>
            </li>
          <% end %>
        </td>
        <td>
          <%= places["latitude"] %>
        </td>
        <td>
          <%= places["longitude"] %>
        </td>
      </tr>
    </table>
    


  <% end %>
  </tr>
<% else %>
  YOU LIVE IN A DESERT JUST ROT AND IED ALREADY <h1>-RESTINPEACEHARAMBE- </h1>
<% end %>

</ul>

app/views/locations/new.html.erb
<%= simple_form_for @location do |f| %>

  <div class="col-xs-6" id="panels" style="border: solid; border-radius: 1px;">
    <div class ="row header-bar">  
      <div class="col-xs-6">
        <h4>Location</h4>
      </div>
    </div>

    <%= f.label :address %>
    <br>
    <%= f.input_field :address, value: current_user.profile.full_address %>
    <br>
    <%= f.label :longitude %>
    <br>
    <%= f.input_field :longitude%>
    <br>
    <%= f.label :latitude %>
    <br>
    <%= f.input_field :latitude%>

    

      <div class ="row footer-bar">  
        <ul class="list-unstyled" id="footers">
          <%= f.submit "Create the location" %>
          </ul>
          
      </div>
    </div>
  </div>

<% end %>

app/views/locations/show.html.erb
<br>
<br>
<br>

<ul>

  <% "Location" %>

  <p>
    <strong>Address:</strong>
    <%= @location.address %>
  </p>
  <p>
    <strong>Latitude:</strong>
    <%= @location.latitude %>
  </p>
  <p>
    <strong>Longitude:</strong>
    <%= @location.longitude %>
  </p>

  <h3>Nearby Locations</h3>
  <ul>
  <% for location in @location.nearbys(10) %>
    <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
  <% end %>
</ul>

<br>

<p>
  <%= link_to "Edit", edit_location_path(@location) %> |
  <%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", locations_path %>
</p>